import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { barrierBlocksMovementLine, barrierBlocksSightLine } from "../app/barrier-geometry.ts";

test("Dust 2 preserves its full-resolution art, surface-aware barriers, elevation, and canvas map lab", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const maps = await readFile(new URL("../app/map-runtime.ts", import.meta.url), "utf8");
  const visibility = await readFile(new URL("../app/dust2-visibility-runtime.ts", import.meta.url), "utf8");
  const data = await readFile(new URL("../app/dust2-map-data.ts", import.meta.url), "utf8");
  const debugOverlay = await readFile(new URL("../app/dust2-debug-overlay.tsx", import.meta.url), "utf8");
  const visionOverlay = await readFile(new URL("../app/battlefield-vision-overlay.tsx", import.meta.url), "utf8");
  const battlefieldVision = await readFile(new URL("../app/battlefield-vision-runtime.ts", import.meta.url), "utf8");
  const objectiveUi = await readFile(new URL("../app/objective-tracker.tsx", import.meta.url), "utf8");
  const traversal = await readFile(new URL("../app/dust2-traversal.ts", import.meta.url), "utf8");
  const playerView = await readFile(new URL("../app/use-battlefield-player-view.ts", import.meta.url), "utf8");
  const geometry = await readFile(new URL("../app/barrier-geometry.ts", import.meta.url), "utf8");
  const barriers = JSON.parse(await readFile(new URL("../app/dust2-barriers.json", import.meta.url), "utf8"));
  const elevation = JSON.parse(await readFile(new URL("../app/dust2-height-map.json", import.meta.url), "utf8"));
  const image = await readFile(new URL("../public/dust2-map.png", import.meta.url));

  assert.match(data, /DUST2_COLS = 33[\s\S]*DUST2_ROWS = 33/);
  assert.equal(barriers.length, 574, "all free-floating AboveVTT barriers should be preserved");
  assert.ok(barriers.every((barrier) =>
    ["wall", "terrain-wall", "door"].includes(barrier.kind) &&
    Number.isFinite(barrier.a?.x) && Number.isFinite(barrier.a?.y) &&
    Number.isFinite(barrier.b?.x) && Number.isFinite(barrier.b?.y)
  ), "barriers should remain arbitrary vector segments instead of snapped tile edges");
  assert.equal(barriers.filter((barrier) => barrier.kind === "wall").length, 286);
  assert.equal(barriers.filter((barrier) => barrier.kind === "terrain-wall").length, 282, "walkable object outlines should preserve their terrain-cover behavior");
  assert.equal(barriers.filter((barrier) => barrier.kind === "door").length, 6);
  assert.deepEqual(barriers.filter((barrier) => barrier.open).map((barrier) => barrier.id), ["above-550", "above-551", "above-552", "above-572", "above-573"], "AboveVTT open doors must not become permanent walls");
  assert.equal(barriers.find((barrier) => barrier.id === "above-571").open, undefined, "the source's closed door should remain closed");
  assert.equal(barriers.filter((barrier) => Number.isFinite(barrier.topFt)).length, 339, "authored wall-top elevations should survive the import");
  assert.equal(barriers.filter((barrier) => Number.isFinite(barrier.bottomFt)).length, 26, "authored wall-bottom elevations should survive the import");
  assert.ok(Math.abs(barriers.find((barrier) => barrier.id === "above-33").b.y - 32.366) < .001, "AboveVTT source coordinates should use scene conversion, not the old drifting DPR guess");
  assert.equal(barriers.find((barrier) => barrier.id === "above-295").kind, "terrain-wall", "object outlines must not become sticky movement walls");
  const coverFrom = { x: 30.5, y: 10.5, zFt: 0 }, coverTo = { x: 31.5, y: 11.5, zFt: 0 };
  assert.equal(barrierBlocksMovementLine(barriers, coverFrom, coverTo), false, "one visible object edge should not block the known Dust 2 cover entry");
  assert.equal(barrierBlocksMovementLine(barriers.filter((barrier) => barrier.kind === "terrain-wall"), coverFrom, { x: 12.5, y: 11.5, zFt: 0 }), false, "terrain cover vectors should never create the grid's muddy movement feeling");
  assert.equal(barrierBlocksSightLine(barriers, { ...coverFrom, zFt: 5 }, { ...coverTo, zFt: 5 }, () => ({ bottomFt: -Infinity, topFt: Infinity })), false, "the same first object edge should remain visible");
  assert.equal(elevation.length, 33);
  assert.ok(elevation.every((row) => row.length === 33), "elevation should cover the complete 33 by 33 map");
  assert.ok(elevation.flat().some((height) => height < 0), "sunken areas should retain negative elevation");
  assert.equal(Math.max(...elevation.flat()), 30, "the highest Dust 2 platforms should retain literal feet");
  assert.equal(elevation[6][2], 9);
  assert.equal(elevation[13][17], 1);
  assert.equal(elevation[17][27], 2);
  assert.equal(elevation[11][26], 22, "ramps and intermediate source heights must not be rounded to five-foot tiers");
  assert.match(data, /dust2PartyStarts = \[\[15, 30\], \[16, 30\], \[14, 30\], \[17, 30\]\]/, "the party should form up across O31-R31 before the T-spawn staircase");
  assert.equal(image.readUInt32BE(16), 2048, "Dust 2 art should retain its source width");
  assert.equal(image.readUInt32BE(20), 2048, "Dust 2 art should retain its source height");
  assert.ok(image.length > 8_000_000, "Dust 2 should use the supplied full-resolution image");

  assert.match(maps, /dust2BlockedMovementTransitions/);
  assert.match(visibility, /dust2RuntimeBarriers = dust2Barriers\.filter/);
  assert.match(visibility, /barrierBlocksSightLine\(dust2BarrierCandidates/);
  assert.match(maps, /zFt: dust2PositionElevation\(point\)/);
  assert.match(visibility, /terrainHorizonBlocksSight/);
  assert.doesNotMatch(maps, /dust2-wall-edges|dust2ElevationAt/);
  assert.match(visibility, /DUST2_UNDERPASS_SURFACE = "bridge-underpass"/);
  assert.match(traversal, /underpass-west-7/);
  assert.match(traversal, /pit-climb-west/);
  assert.match(traversal, /blue-square-climb/);
  assert.match(traversal, /dust2MoverStepCostSquares/);
  assert.match(traversal, /dust2ForcedMoveDestination/);
  assert.match(traversal, /dust2SharesSurface/);
  assert.match(geometry, /const onSegment =/);
  assert.match(geometry, /Math\.abs\(abC\) <= EPSILON && onSegment/);
  assert.match(page, /const dust2MapPlaytest = !campaign && dust2MapActive && !enemyTypes\.length/);
  assert.match(page, /dust2MapPlaytest && dust2FreeClimb/);
  assert.match(page, /dust2MapActive && <Dust2DebugOverlay debug=\{dust2MapPlaytest\} walls=\{dust2ShowWalls\} elevation=\{dust2ShowElevation\} grid=\{dust2ShowGridLines\}/);
  assert.match(page, /\[dust2ShowGridLines, setDust2ShowGridLines\] = useState\(false\)/);
  assert.match(page, /setDust2ShowGridLines\(false\)/);
  assert.match(page, /Dust 2 Map Lab/);
  assert.match(page, /const boardTilePixels = dust2MapActive \? 60 : 52/);
  assert.match(page, /"--tile-pixels": `\$\{boardTilePixels\}px`/);
  assert.match(page, /animatedDust2Walk \? 75 : 140/, "Dust 2 path animation should respond briskly without teleporting");
  assert.match(page, /playerView\.hasLineOfSight/);
  assert.match(page, /playerView\.isUnitVisible\(u\)/);
  assert.match(page, /playerView\.isUnitVisible\(unit\)/);
  assert.match(page, /playerView\.isUnitVisible\(inspected\)/);
  assert.match(page, /playerView\.tileState\(x, y\) !== "unexplored" \|\| attackDist\(active, \{ x, y \}\) <= 1/);
  assert.match(page, /playerViewAllowsStep\(mover, from, to\)/);
  assert.match(page, /playerViewAllowsStep\(active, from, to\)/);
  assert.match(page, /playerView\.tileState\(from\.x, from\.y\) !== "unexplored"[\s\S]{0,120}playerView\.tileState\(to\.x, to\.y\) !== "unexplored" \|\| attackDist\(from, to\) <= 1/);
  assert.match(page, /dust2PositionsAt\(x, y\)\.every\(positionOccupied\)/);
  assert.match(page, /clickedMoveDestination[\s\S]{0,400}dust2SharesSurface\(u, clickedMoveDestination\)/);
  assert.match(page, /Object\.assign\(companion, companionSpot, dust2MapActive \? dust2PositionState\(companionSpot\)/);
  assert.match(page, /player-view-visible-token/);
  assert.match(page, /movementStepCost\(mover, from, to\)/);
  assert.match(page, /dust2PreferredPositionAt\(active, x, y\)/);
  assert.match(page, /dust2SamePosition\(moved, target\)/);
  assert.match(page, /dust2SamePosition\(point, moved\)/);
  assert.match(page, /dust2SamePosition\(step, movedUnit\)/);
  assert.match(page, /const isGoal = dust2MapActive \? dust2SamePosition\(to, goal\)/);
  assert.match(page, /rollFallDamage\(dropFt,[\s\S]*athleticSafeFallFeet\(target\)/);
  assert.match(playerView, /useState\(true\)/, "Player View should default on");
  assert.match(playerView, /combinePlayerVisionMasks/);
  assert.match(playerView, /mergeExploredMask/);
  assert.match(playerView, /surfaceId:\s*unit\.surfaceId/);
  assert.match(playerView, /battlefieldPositionAt\(battlefield, observer, x, y\)/);
  assert.match(battlefieldVision, /battlefield\.id === "dust2"[\s\S]*dust2PreferredPositionAt/);
  assert.match(playerView, /conditionLimitsVision\(unit\) \? 1/);
  assert.match(playerView, /zone\.blocksVision/);
  assert.match(page, /Walls \{dust2ShowWalls \? "ON" : "OFF"\}/);
  assert.match(page, /Elevation \{dust2ShowElevation \? "ON" : "OFF"\}/);
  assert.match(page, /Free Climb \{dust2FreeClimb \? "ON" : "OFF"\}/);
  assert.match(debugOverlay, /Dust2GeometryCanvas/);
  assert.doesNotMatch(debugOverlay, /Dust2VisionCanvas|new window\.Image/, "Dust 2 should not redraw the map image behind fog");
  assert.match(visionOverlay, /FOG_TILE = 52/, "fog should render at the board's native resolution for smooth sub-tile wall shadows");
  assert.match(page, /<BattlefieldVisionOverlay view=\{playerView\}/);
  assert.match(page, /dust2ShowElevation, setDust2ShowElevation\] = useState\(true\)/, "playtest elevation should be visible by default");
  assert.doesNotMatch(debugOverlay, /<button|useState\(/, "the Dust 2 overlay should be canvas-only and never cover the map with its own controls");
  assert.match(visionOverlay, /tracePolygon\(context, polygon\)[\s\S]*context\.clip\(\)/, "player vision should clip fog along vector wall angles instead of whole tile edges");
  assert.match(page, /levelTwoMode[\s\S]{0,120}dust2MapActive/);
  assert.match(objectiveUi, /Recover The One True Flag/);
  assert.match(objectiveUi, /Plant at Site A or B/);
  assert.match(page, /DUST2_SECRET_EXIT\.coordinate/);
  assert.match(debugOverlay, /canvas\.width !== width/);
  assert.match(visionOverlay, /useLayoutEffect/);
  assert.match(debugOverlay, /barrier\.kind === "terrain-wall"/);
  assert.match(debugOverlay, /dust2HeightMap\.forEach/);
  assert.doesNotMatch(debugOverlay, /height \* 5/);
  assert.match(debugOverlay, /dust2Barriers\.forEach/);
  assert.doesNotMatch(debugOverlay, /dust2-height-label|<svg|<line/);
  assert.doesNotMatch(debugOverlay, /rgba\(0, 0, 0, \.98\)/);
  assert.match(page, /Continue Without Enemies/);
  assert.doesNotMatch(page, /disabled=\{!enemyTypes\.length\}[\s\S]{0,120}setStage\("maps"\)/);
});
