export type AbilityVfxGeometry = "point" | "line" | "area";

export const ABILITY_VFX_ASSETS: Readonly<Record<string, string>> = {
  "Solar Beam": "solar-beam", "Thorn Lash": "thorn-lash", "Chaos Lance": "chaos-lance", "Ice Spear": "frost-lance", "Frost Lance": "frost-lance", "Ground Breaker": "ground-breaker", "Spike Growth": "spike-growth", "Sanctuary": "sanctuary", "Run it Back, Turbo": "lay-on-hands",
  "Dissonant Whispers": "dissonant-whispers", "Restoring Chorus": "restoring-chorus", "Driving Strike": "driving-strike", "Bardic Inspiration": "bardic-inspiration", "Healing Verse": "healing-verse", "Discordant Note": "discordant-note",
  "Mending Light": "sanctuary", "Radiant Bolt": "solar-beam", "Arcane Bolt": "arcane-bolt", "Drain": "drain", "Ward": "ward", "Moon Mend": "moon-mend", "Wildfire": "wildfire", "Second Wind": "second-wind", "Sneak Attack": "sneak-attack-v2.png", "Fire Bolt": "fire-bolt", "Shield": "shield",
  "Acid Breath": "acid-breath", "Lightning Absorption": "lightning-absorption", "Tail Spike": "tail-spike", "Tailstorm": "tailstorm.png", "Living Shroud Strike": "living-shroud-strike",
  "Flurry of Blows": "flurry-of-blows", "Open Palm": "open-palm", "Patient Defense": "patient-defense", "Divine Smite": "divine-smite", "Lay on Hands": "lay-on-hands", "Hunter's Mark": "hunters-mark", "Ensnaring Strike": "ensnaring-strike", "Eldritch Blast": "eldritch-blast", "Hex": "hex", "Armor of Agathys": "armor-of-agathys",
  "Sweeping Kick": "sweeping-kick", "Shielding Smite": "shielding-smite", "Thunderous Smite": "thunderous-smite", "Hail of Thorns": "hail-of-thorns", "Field Remedy": "field-remedy", "Hellish Rebuke": "hellish-rebuke", "Arms of Hadar": "arms-of-hadar", "Throwing Knife": "throwing-knife", "Reckless Blow": "reckless-blow", "Battle Rush": "battle-rush",
  "Leap of the Clouds": "leap-of-the-clouds", "Stunning Strike": "stunning-strike", "Branding Smite": "branding-smite", "Turn the Unholy": "turn-the-unholy", "Lesser Restoration": "lesser-restoration", "Fog Cloud": "fog-cloud", "Goodberry": "goodberry", "Longstrider": "longstrider", "Misty Step": "misty-step", "Shatter": "shatter", "Toll the Dead": "toll-the-dead",
  "Unbroken": "unbroken", "Crushing Blow": "crushing-blow", "Reckless Cleave": "reckless-cleave", "Pinning Strike": "pinning-strike", "Counterstance": "counterstance", "Fan of Knives": "fan-of-knives", "Wholeness of Body": "wholeness-of-body", "Blinding Smite": "blinding-smite", "Hold Person": "hold-person", "Zephyr Strike": "zephyr-strike",
  "Darkness": "darkness", "Invisibility": "invisibility", "Counterspell": "counterspell", "Hunger of Hadar": "hunger-of-hadar", "Fear": "fear.png", "Vampiric Touch": "vampiric-touch.png", "Blight": "blight.png", "Lightning Arrow": "lightning-arrow.png", "Animal Companion": "animal-companion.png", "Flame Arrows": "flame-arrows.png", "Healing Spirit": "healing-spirit.png", "Wind Wall": "wind-wall.png", "Plant Growth": "plant-growth.png", "Volley": "volley.png",
  "Starfall": "starfall.png", "Disintegrate": "disintegrate.png", "Searing Light": "searing-light.png", "Thunderclap": "thunderclap.png", "Life Bloom": "life-bloom.png", "Greater Mend": "greater-mend.png", "Arcane Renewal": "arcane-renewal.png", "Crimson Renewal": "crimson-renewal.png", "Renewal": "renewal.png", "Massive Cure": "massive-cure.png", "Ember Ward": "ember-ward.png", "Judgment": "judgment.png",
  "Blood Roar": "blood-roar.png", "Cutting Refrain": "cutting-refrain.png", "Forked Flame": "forked-flame.png", "Gale Burst": "gale-burst.png", "Piercing Note": "piercing-note.png", "Sacred Hammer": "sacred-hammer.png", "Heroic Verse": "heroic-verse.png", "Stone Fang": "stone-fang.png", "Indomitable": "indomitable.png", "Lunging Thrust": "lunging-thrust.png", "Hamstring": "hamstring.png", "Assassinate": "assassinate.png",
  "Twinned Spell": "twinned-spell.png", "Distant Spell": "distant-spell.png", "Heightened Spell": "heightened-spell.png", "Favored Enemy": "favored-enemy.png",
};

export const ANIMATED_ABILITY_EFFECTS = new Set(["Sneak Attack", "Fear", "Vampiric Touch", "Blight", "Lightning Arrow", "Animal Companion", "Flame Arrows", "Volley", "Starfall", "Disintegrate", "Searing Light", "Thunderclap", "Life Bloom", "Greater Mend", "Arcane Renewal", "Crimson Renewal", "Renewal", "Massive Cure", "Ember Ward", "Judgment", "Blood Roar", "Cutting Refrain", "Forked Flame", "Gale Burst", "Piercing Note", "Sacred Hammer", "Heroic Verse", "Stone Fang", "Indomitable", "Lunging Thrust", "Hamstring", "Assassinate"]);
export const LINE_ABILITY_EFFECTS = new Set(["Solar Beam", "Thorn Lash", "Chaos Lance", "Ice Spear", "Frost Lance", "Healing Verse", "Discordant Note", "Radiant Bolt", "Arcane Bolt", "Drain", "Fire Bolt", "Eldritch Blast", "Throwing Knife", "Leap of the Clouds", "Misty Step", "Zephyr Strike", "Counterspell", "Disintegrate", "Searing Light", "Blood Roar", "Cutting Refrain", "Forked Flame", "Gale Burst", "Piercing Note", "Lunging Thrust", "Hamstring", "Assassinate", "Wind Wall"]);
export const AREA_ABILITY_EFFECTS = new Set(["Hail of Thorns", "Arms of Hadar", "Fog Cloud", "Shatter", "Fan of Knives", "Reckless Cleave", "Darkness", "Hunger of Hadar", "Plant Growth", "Healing Spirit", "Turn the Unholy", "Fear", "Volley"]);
export const MONSTER_LINE_EFFECTS = new Set(["Acid Breath", "Tail Spike"]);
export const MONSTER_AREA_EFFECTS = new Set(["Engulf", "Tailstorm", "Whirlwind Slam"]);
export const MONSTER_DETACHED_EFFECTS = new Set([...MONSTER_LINE_EFFECTS, ...MONSTER_AREA_EFFECTS, "Regeneration", "Lightning Absorption", "Living Shroud Strike"]);
export const SPECIAL_RENDERED_EFFECTS = new Set(["Rage", "Fireball", "Lightning Bolt"]);
export const PASSIVE_BADGE_ASSETS = { "Twinned Spell": "twinned-spell", "Distant Spell": "distant-spell", "Heightened Spell": "heightened-spell", "Favored Enemy": "favored-enemy" } as const;

export const abilityVfxGeometry = (name: string): AbilityVfxGeometry =>
  LINE_ABILITY_EFFECTS.has(name) || MONSTER_LINE_EFFECTS.has(name) ? "line" : AREA_ABILITY_EFFECTS.has(name) || MONSTER_AREA_EFFECTS.has(name) || name === "Spike Growth" ? "area" : "point";
export const hasAbilityVfx = (name: string) => !!ABILITY_VFX_ASSETS[name] || SPECIAL_RENDERED_EFFECTS.has(name);
export const abilityVfxAssetUrl = (name: string) => { const asset = ABILITY_VFX_ASSETS[name]; return asset ? `/vfx-${asset.includes(".") ? asset : `${asset}.webp`}` : undefined; };
