"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { pointToBarrierDistance, type BarrierPoint, type FreeBarrier } from "./barrier-geometry";
import { DUST2_COLS, DUST2_IMAGE, DUST2_ROWS, dust2Barriers, dust2HeightMap, dust2PartyStarts } from "./dust2-map-data";
import MapEditorVisionOverlay from "./map-editor-vision-overlay";
import { createEditorPlaytestVisionKernel, editorPlaytestObserver, editorPlaytestTarget, findEditorPlaytestRoute } from "./map-editor-playtest";
import { fallDiceForDrop } from "./elevation-rules";

type TileKind = "void"|"floor"|"dungeon"|"grass"|"forest"|"moss"|"dirt"|"stone"|"ritual-stone"|"water"|"bridge"|"ruin"|"difficult"|"lava"|"ice"|"poison"|"wall"|"door"|"pillar"|"stairs-up"|"stairs-down"|"tree"|"rock"|"barricade";
type MarkerKind = "party-start"|"enemy-spawn"|"npc-spawn"|"ritual"|"objective"|"discovery"|"trap"|"exit"|"note";
type Marker = { kind: MarkerKind; label?: string; group?: string };
type Tile = { kind: TileKind; elevationFt?: number; blocked?: boolean; marker?: Marker; label?: string };
type LegacyTile = Tile & { elevation?: number };
type EdgeSide = "n"|"e"|"s"|"w"|"nw-se"|"ne-sw"; type MapEdge = {x:number;y:number;side:EdgeSide;kind:"wall"|"door"|"secret-door"};
type MapData = {format:"shattered-crown-map";version:1|2|3|4|5|6;name:string;width:number;height:number;tiles:LegacyTile[];edges?:MapEdge[];barriers?:FreeBarrier[];image?:string};
type ElevationBrush = `elevation-${number}`;
type Brush = TileKind|MarkerKind|"blocked"|"unblocked"|ElevationBrush|"wall-line"|"door-line"|"secret-door-line"|"erase-line"|"free-wall-line"|"free-terrain-line"|"free-door-line"|"free-secret-door-line"|"erase-free-line"|"erase-marker";
type Tool = {kind:Brush;icon:string;label:string;key?:string};
const geometry:Tool[]=[{kind:"floor",icon:"·",label:"Floor",key:"F"},{kind:"dungeon",icon:"▦",label:"Dungeon floor",key:"H"},{kind:"pillar",icon:"●",label:"Pillar",key:"P"},{kind:"stairs-up",icon:"↗",label:"Stairs up",key:"U"},{kind:"stairs-down",icon:"↘",label:"Stairs down",key:"J"},{kind:"void",icon:"×",label:"Erase tile",key:"E"}];
const outdoors:Tool[]=[{kind:"grass",icon:"♧",label:"Grass",key:"G"},{kind:"forest",icon:"♣",label:"Forest"},{kind:"moss",icon:"❧",label:"Moss"},{kind:"dirt",icon:"∴",label:"Dirt",key:"I"},{kind:"stone",icon:"◆",label:"Stone"},{kind:"ritual-stone",icon:"◉",label:"Ritual stone"},{kind:"water",icon:"≈",label:"Water"},{kind:"bridge",icon:"═",label:"Bridge"},{kind:"ruin",icon:"▧",label:"Ruins"},{kind:"difficult",icon:"≋",label:"Difficult ground"},{kind:"tree",icon:"♠",label:"Tree"},{kind:"rock",icon:"⬟",label:"Rock"},{kind:"barricade",icon:"╳",label:"Barricade"}];
const elements:Tool[]=[{kind:"lava",icon:"≈",label:"Lava",key:"L"},{kind:"ice",icon:"◇",label:"Ice",key:"C"},{kind:"poison",icon:"☣",label:"Poison",key:"O"}];
const markers:Tool[]=[{kind:"party-start",icon:"◆",label:"Party start",key:"S"},{kind:"enemy-spawn",icon:"♟",label:"Enemy spawn",key:"M"},{kind:"npc-spawn",icon:"♙",label:"NPC spawn",key:"N"},{kind:"ritual",icon:"✺",label:"Ritual"},{kind:"objective",icon:"★",label:"Objective"},{kind:"discovery",icon:"?",label:"Discovery"},{kind:"trap",icon:"⌁",label:"Trap",key:"T"},{kind:"exit",icon:"➜",label:"Exit"},{kind:"note",icon:"#",label:"Room / note",key:"R"},{kind:"erase-marker",icon:"⌫",label:"Erase marker"}];
const elevations:Tool[]=[-10,-5,0,5,10,15,20,25,30].map(feet=>({kind:`elevation-${feet}` as Brush,icon:String(feet),label:`${feet} ft`}));
const all=[...geometry,...outdoors,...elements,...markers,...elevations];
const markerKinds=new Set<Brush>(markers.map(t=>t.kind).filter(k=>k!=="erase-marker"));
const lineKinds=new Set<Brush>(["wall-line","door-line","secret-door-line","erase-line"]);
const freeLineKinds=new Set<Brush>(["free-wall-line","free-terrain-line","free-door-line","free-secret-door-line","erase-free-line"]);
const drawingKinds=new Set<Brush>([...lineKinds,...freeLineKinds]);
const blockedDefault=new Set<TileKind>(["void","wall","pillar","tree","rock","barricade","water","lava"]);
const sightBlockingDefault=new Set<TileKind>(["void","wall","pillar","tree","rock","barricade"]);
const blank=(w:number,h:number):Tile[]=>Array.from({length:w*h},()=>({kind:"void",elevationFt:0}));
const normalize=(raw:LegacyTile,legacyTiers=false):Tile=>{const legacy:Record<string,MarkerKind>={spawn:"party-start",enemy:"enemy-spawn",npc:"npc-spawn",trap:"trap",note:"note"},{elevation:legacyElevation,...tile}=raw,m=legacy[raw.kind],source=Number.isFinite(raw.elevationFt)?raw.elevationFt||0:Number.isFinite(legacyElevation)?(legacyElevation||0)*(legacyTiers?5:1):0,elevationFt=Math.max(-500,Math.min(500,source));return m?{kind:"floor",elevationFt:0,marker:{kind:m,label:raw.label}}:{...tile,elevationFt};};
const cloneBarriers=(items:readonly FreeBarrier[])=>(items||[]).filter(item=>item&&Number.isFinite(item.a?.x)&&Number.isFinite(item.a?.y)&&Number.isFinite(item.b?.x)&&Number.isFinite(item.b?.y)).map(item=>({...item,a:{...item.a},b:{...item.b}}));
const icon=(kind?:string)=>all.find(t=>t.kind===kind)?.icon||"";
const draftKey="shattered-crown-map-editor-v3";
const dust2EditorTiles=()=>{const startKeys=new Set(dust2PartyStarts.map(([x,y])=>`${x},${y}`));return Array.from({length:DUST2_COLS*DUST2_ROWS},(_,i)=>{const x=i%DUST2_COLS,y=Math.floor(i/DUST2_COLS);return {kind:"stone" as TileKind,elevationFt:dust2HeightMap[y]?.[x]||0,blocked:false,marker:startKeys.has(`${x},${y}`)?{kind:"party-start" as MarkerKind,label:"T Spawn"}:undefined};});};
function ToolButtons({items,brush,onSelect}:{items:Tool[];brush:Brush;onSelect:(brush:Brush)=>void}){return <div className="tool-grid">{items.map(t=><button key={t.kind} className={brush===t.kind?"selected":""} onClick={()=>onSelect(t.kind)} title={`${t.label}${t.key?` (${t.key})`:""}`}><i>{t.icon}</i><span>{t.label}{t.key&&<small>{t.key}</small>}</span></button>)}</div>;}

export default function MapEditor({onExit,initialDust2=false}:{onExit:()=>void;initialDust2?:boolean}){
 const [name,setName]=useState(initialDust2?"Dust 2":"New Encounter Map"),[width,setWidth]=useState(initialDust2?DUST2_COLS:20),[height,setHeight]=useState(initialDust2?DUST2_ROWS:16),[tiles,setTiles]=useState<Tile[]>(()=>initialDust2?dust2EditorTiles():blank(20,16)),[edges,setEdges]=useState<MapEdge[]>([]),[barriers,setBarriers]=useState<FreeBarrier[]>(()=>initialDust2?cloneBarriers(dust2Barriers):[]),[brush,setBrush]=useState<Brush>(initialDust2?"elevation-0":"grass"),[zoom,setZoom]=useState(initialDust2?24:32);
 const [painting,setPainting]=useState(false),[history,setHistory]=useState<{tiles:Tile[];edges:MapEdge[];barriers:FreeBarrier[]}[]>([]),[future,setFuture]=useState<{tiles:Tile[];edges:MapEdge[];barriers:FreeBarrier[]}[]>([]),[reference,setReference]=useState<string|null>(initialDust2?DUST2_IMAGE:null),[opacity,setOpacity]=useState(initialDust2?.82:.45),[preview,setPreview]=useState(false),[showTileData,setShowTileData]=useState(initialDust2),[snapVertex,setSnapVertex]=useState<{x:number;y:number}|null>(null),[wallHeightFt,setWallHeightFt]=useState(10),[exactElevationFt,setExactElevationFt]=useState(1),[freeBarrierDraft,setFreeBarrierDraft]=useState<{a:BarrierPoint;b:BarrierPoint;kind:FreeBarrier["kind"];heightFt:number}|null>(null),[showBarrierLayer,setShowBarrierLayer]=useState(true),[showElevationLayer,setShowElevationLayer]=useState(true),[showGridLayer,setShowGridLayer]=useState(true),[freeClimb,setFreeClimb]=useState(true),[sightProbe,setSightProbe]=useState(false),[testToken,setTestToken]=useState<BarrierPoint|null>(null),[testRoute,setTestRoute]=useState<BarrierPoint[]>([]),[testSightTarget,setTestSightTarget]=useState<BarrierPoint|null>(null),[testSightVisible,setTestSightVisible]=useState<boolean|null>(null),[message,setMessage]=useState(initialDust2?"Dust 2 ready. Choose an elevation preset or enter exact feet, then click-drag directly on the map.":"Paint terrain, then add elevation and encounter markers as separate layers.");
 const fileRef=useRef<HTMLInputElement>(null),importRef=useRef<HTMLInputElement>(null),strokeRef=useRef(false),lineDrawingRef=useRef(false),lastVertexRef=useRef<{x:number;y:number}|null>(null),freeBarrierDraftRef=useRef<{a:BarrierPoint;b:BarrierPoint;kind:FreeBarrier["kind"];heightFt:number}|null>(null);
 useEffect(()=>{if(initialDust2)return;const id=setTimeout(()=>{try{const raw=localStorage.getItem(draftKey);if(!raw)return;const d=JSON.parse(raw) as MapData;if(d.format==="shattered-crown-map"&&d.tiles.length===d.width*d.height){setName(d.name);setWidth(d.width);setHeight(d.height);setTiles(d.tiles.map(tile=>normalize(tile,d.version<6)));setEdges(d.edges||[]);setBarriers(cloneBarriers(d.barriers||[]));setReference(d.image||null);setMessage("Recovered your last local draft.");}}catch{}},0);return()=>clearTimeout(id);},[initialDust2]);
 useEffect(()=>{const id=setTimeout(()=>localStorage.setItem(draftKey,JSON.stringify({format:"shattered-crown-map",version:6,name,width,height,tiles,edges,barriers,image:reference?.startsWith("/")?reference:undefined})),250);return()=>clearTimeout(id);},[name,width,height,tiles,edges,barriers,reference]);
 const counts=useMemo(()=>({raised:tiles.filter(t=>(t.elevationFt||0)>0).length,markers:tiles.filter(t=>t.marker).length,forest:tiles.filter(t=>t.kind==="forest").length,barriers:barriers.length}),[tiles,barriers]);
 const edgesByTile=useMemo(()=>{const indexed=new Map<string,MapEdge[]>();edges.forEach(edge=>{const tileKey=`${edge.x},${edge.y}`;indexed.set(tileKey,[...(indexed.get(tileKey)||[]),edge]);});return indexed;},[edges]);
 const editorTestTiles=useMemo(()=>tiles.map(tile=>({blocked:tile.blocked??blockedDefault.has(tile.kind),blocksSight:sightBlockingDefault.has(tile.kind),elevationFt:tile.elevationFt||0})),[tiles]);
 const editorVisionKernel=useMemo(()=>createEditorPlaytestVisionKernel({width,height,tiles:editorTestTiles,edges,barriers}),[barriers,edges,editorTestTiles,height,width]);
 const playtestVision=useMemo(()=>preview&&testToken?editorVisionKernel.layerFor(editorPlaytestObserver({point:testToken,width,tiles:editorTestTiles}),null):null,[editorTestTiles,editorVisionKernel,preview,testToken,width]);
 const snapshot=()=>{if(strokeRef.current)return;strokeRef.current=true;setHistory(h=>[...h.slice(-39),{tiles:tiles.map(t=>({...t,marker:t.marker&&{...t.marker}})),edges:edges.map(e=>({...e})),barriers:cloneBarriers(barriers)}]);setFuture([]);};
 const markerPrompt=(kind:MarkerKind,current?:Marker):Marker|null=>{const grouped=kind==="enemy-spawn"||kind==="npc-spawn";const text=kind==="discovery"?"Discovery text (use Animal Tracks for Ranger-visible tracks)":kind==="ritual"?"Ritual name":kind==="objective"?"Objective name":kind==="exit"?"Exit destination":grouped?"Spawn group/name (example: opening-wolves)":kind==="note"?"Room number or note":"Optional marker label";const value=prompt(text,current?.group||current?.label||"");if(value===null)return null;return grouped?{kind,group:value.trim()||undefined}:{kind,label:value.trim()||undefined};};
 const paint=(i:number)=>{snapshot();setTiles(cur=>{const next=[...cur],old=cur[i]||{kind:"void",elevationFt:0};if(markerKinds.has(brush)){const marker=markerPrompt(brush as MarkerKind,old.marker);if(!marker)return cur;next[i]={...old,marker};}else if(brush==="erase-marker")next[i]={...old,marker:undefined};else if(brush.startsWith("elevation-"))next[i]={...old,elevationFt:Number(brush.slice("elevation-".length))};else if(brush==="blocked"||brush==="unblocked")next[i]={...old,blocked:brush==="blocked"};else next[i]={...old,kind:brush as TileKind,blocked:undefined};return next;});};
 const segmentFor=(a:{x:number;y:number},b:{x:number;y:number}):Omit<MapEdge,"kind">|null=>{const dx=b.x-a.x,dy=b.y-a.y;if(Math.abs(dx)>1||Math.abs(dy)>1||(!dx&&!dy))return null;if(!dy){const x=Math.min(a.x,b.x),y=a.y;return y===height?{x,y:height-1,side:"s"}:{x,y,side:"n"};}if(!dx){const x=a.x,y=Math.min(a.y,b.y);return x===width?{x:width-1,y,side:"e"}:{x,y,side:"w"};}const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y);return {x,y,side:dx===dy?"nw-se":"ne-sw"};};
 const drawSegment=(a:{x:number;y:number},b:{x:number;y:number})=>{const n=segmentFor(a,b);if(!n)return;setEdges(cur=>{const without=cur.filter(e=>!(e.x===n.x&&e.y===n.y&&e.side===n.side));const kind:MapEdge["kind"]=brush==="door-line"?"door":brush==="secret-door-line"?"secret-door":"wall";return brush==="erase-line"?without:[...without,{...n,kind}];});};
 const pointerVertex=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(width,Math.round((e.clientX-r.left)/zoom))),y:Math.max(0,Math.min(height,Math.round((e.clientY-r.top)/zoom)))};};
 const pointerPoint=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(width,(e.clientX-r.left)/zoom)),y:Math.max(0,Math.min(height,(e.clientY-r.top)/zoom))};};
 const magnetizeFreePoint=(point:BarrierPoint)=>{let snapped=point,distance=9/zoom;barriers.flatMap(barrier=>[barrier.a,barrier.b]).forEach(endpoint=>{const candidate=Math.hypot(point.x-endpoint.x,point.y-endpoint.y);if(candidate<distance){distance=candidate;snapped={...endpoint};}});return snapped;};
 const freeBarrierKind=():FreeBarrier["kind"]=>brush==="free-terrain-line"?"terrain-wall":brush==="free-door-line"?"door":brush==="free-secret-door-line"?"secret-door":"wall";
 const eraseNearestBarrier=(point:BarrierPoint)=>setBarriers(cur=>{let nearest=-1,distance=10/zoom;cur.forEach((barrier,index)=>{const candidate=pointToBarrierDistance(point,barrier);if(candidate<=distance){nearest=index;distance=candidate;}});return nearest<0?cur:cur.filter((_,index)=>index!==nearest);});
 const continueLine=(target:{x:number;y:number})=>{const startingVertex=lastVertexRef.current;if(!startingVertex){lastVertexRef.current=target;return;}let from:{x:number;y:number}=startingVertex;while(from.x!==target.x||from.y!==target.y){const next:{x:number;y:number}={x:from.x+Math.sign(target.x-from.x),y:from.y+Math.sign(target.y-from.y)};drawSegment(from,next);from=next;}lastVertexRef.current=target;};
 const startLine=(e:React.PointerEvent<HTMLDivElement>)=>{if(!drawingKinds.has(brush)||preview)return;e.preventDefault();snapshot();lineDrawingRef.current=true;setPainting(true);e.currentTarget.setPointerCapture(e.pointerId);if(freeLineKinds.has(brush)){const rawPoint=pointerPoint(e),point=brush==="erase-free-line"?rawPoint:magnetizeFreePoint(rawPoint);if(brush==="erase-free-line")eraseNearestBarrier(point);else{const draft={a:point,b:point,kind:freeBarrierKind(),heightFt:wallHeightFt};freeBarrierDraftRef.current=draft;setFreeBarrierDraft(draft);}}else lastVertexRef.current=pointerVertex(e);};
 const moveLine=(e:React.PointerEvent<HTMLDivElement>)=>{if(!drawingKinds.has(brush)||preview)return;if(freeLineKinds.has(brush)){if(!lineDrawingRef.current)return;e.preventDefault();const rawPoint=pointerPoint(e),point=brush==="erase-free-line"?rawPoint:magnetizeFreePoint(rawPoint);if(brush==="erase-free-line")eraseNearestBarrier(point);else if(freeBarrierDraftRef.current){const draft={...freeBarrierDraftRef.current,b:point};freeBarrierDraftRef.current=draft;setFreeBarrierDraft(draft);}return;}const target=pointerVertex(e);setSnapVertex(target);if(!lineDrawingRef.current)return;e.preventDefault();continueLine(target);};
 const endStroke=()=>{const draft=freeBarrierDraftRef.current;if(draft&&Math.hypot(draft.b.x-draft.a.x,draft.b.y-draft.a.y)>.03){const x=Math.max(0,Math.min(width-1,Math.floor((draft.a.x+draft.b.x)/2))),y=Math.max(0,Math.min(height-1,Math.floor((draft.a.y+draft.b.y)/2))),bottomFt=tiles[y*width+x]?.elevationFt||0;setBarriers(cur=>[...cur,{...draft,bottomFt,topFt:bottomFt+draft.heightFt,id:`barrier-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}]);}setPainting(false);lineDrawingRef.current=false;lastVertexRef.current=null;freeBarrierDraftRef.current=null;setFreeBarrierDraft(null);strokeRef.current=false;};
 const undo=()=>setHistory(h=>{if(!h.length)return h;const p=h[h.length-1];setFuture(f=>[{tiles,edges,barriers:cloneBarriers(barriers)},...f].slice(0,40));setTiles(p.tiles);setEdges(p.edges);setBarriers(cloneBarriers(p.barriers));return h.slice(0,-1);});
 const redo=()=>setFuture(f=>{if(!f.length)return f;const n=f[0];setHistory(h=>[...h,{tiles,edges,barriers:cloneBarriers(barriers)}].slice(-40));setTiles(n.tiles);setEdges(n.edges);setBarriers(cloneBarriers(n.barriers));return f.slice(1);});
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).tagName==="INPUT")return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();if(e.shiftKey)redo();else undo();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo();return;}const t=all.find(x=>x.key?.toLowerCase()===e.key.toLowerCase());if(t)setBrush(t.kind);};addEventListener("keydown",key);return()=>removeEventListener("keydown",key);});
 const resize=()=>{const ow=width,oh=height,w=Math.max(8,Math.min(120,width)),h=Math.max(8,Math.min(120,height));setWidth(w);setHeight(h);setTiles(old=>Array.from({length:w*h},(_,i)=>{const x=i%w,y=Math.floor(i/w);return x<ow&&y<oh?old[y*ow+x]||{kind:"void",elevationFt:0}:{kind:"void",elevationFt:0};}));setEdges(old=>old.filter(e=>e.x<w&&e.y<h));setBarriers(old=>old.filter(barrier=>[barrier.a,barrier.b].every(point=>point.x>=0&&point.y>=0&&point.x<=w&&point.y<=h)));setHistory([]);setFuture([]);setTestToken(null);setTestRoute([]);setMessage(`Canvas resized to ${w} × ${h}.`);};
 const doubleMap=()=>{if(width*2>120||height*2>120){setMessage("This map is too large to double; the maximum canvas is 120 × 120.");return;}snapshot();const oldWidth=width,newWidth=width*2,newHeight=height*2;setTiles(old=>Array.from({length:newWidth*newHeight},(_,i)=>{const nx=i%newWidth,ny=Math.floor(i/newWidth),tile=old[Math.floor(ny/2)*oldWidth+Math.floor(nx/2)]||{kind:"void",elevationFt:0};return {...tile,marker:nx%2===0&&ny%2===0&&tile.marker?{...tile.marker}:undefined};}));setEdges(old=>old.flatMap(e=>{const x=e.x*2,y=e.y*2;if(e.side==="n"||e.side==="s")return [{...e,x,y},{...e,x:x+1,y}];if(e.side==="e"||e.side==="w")return [{...e,x,y},{...e,x,y:y+1}];if(e.side==="nw-se")return [{...e,x,y},{...e,x:x+1,y:y+1}];return [{...e,x:x+1,y},{...e,x,y:y+1}];}));setBarriers(old=>old.map(barrier=>({...barrier,a:{x:barrier.a.x*2,y:barrier.a.y*2},b:{x:barrier.b.x*2,y:barrier.b.y*2}})));setWidth(newWidth);setHeight(newHeight);setHistory([]);setFuture([]);setTestToken(null);setTestRoute([]);setMessage(`Map doubled to ${newWidth} × ${newHeight}. Every original square is now a 2 × 2 playable area.`);};
 const resetMap=()=>{if(!confirm("Reset Level Forge to a blank 20 × 16 map? This clears the current draft."))return;setName("New Encounter Map");setWidth(20);setHeight(16);setTiles(blank(20,16));setEdges([]);setBarriers([]);setReference(null);setPreview(false);setShowTileData(false);setBrush("grass");setHistory([]);setFuture([]);setSnapVertex(null);setTestToken(null);setTestRoute([]);localStorage.removeItem(draftKey);setMessage("Level Forge reset to the default blank map.");};
 const exportMap=()=>{const entered=prompt("Name this map",name==="New Encounter Map"?"":name);if(entered===null)return;const exportName=entered.trim();if(!exportName){setMessage("Give the map a name before exporting it.");return;}setName(exportName);const data:MapData={format:"shattered-crown-map",version:6,name:exportName,width,height,tiles,edges,barriers,image:reference?.startsWith("/")?reference:undefined},blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${exportName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"map"}.json`;a.click();URL.revokeObjectURL(url);setMessage(`“${exportName}” exported with ${barriers.length} free barriers and literal-foot elevation.`);};
 const exportElevation=()=>{const heightMap=Array.from({length:height},(_,y)=>Array.from({length:width},(_,x)=>tiles[y*width+x]?.elevationFt||0)),blob=new Blob([JSON.stringify(heightMap,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"map"}-elevation.json`;a.click();URL.revokeObjectURL(url);setMessage("Elevation exported as a runtime-ready literal-foot height map. Upload that file when you want the built-in map updated.");};
 const loadMap=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(String(reader.result)) as MapData;if(d.format!=="shattered-crown-map"||d.tiles.length!==d.width*d.height)throw Error();setName(d.name);setWidth(d.width);setHeight(d.height);setTiles(d.tiles.map(tile=>normalize(tile,d.version<6)));setEdges(d.edges||[]);setBarriers(cloneBarriers(d.barriers||[]));setReference(d.image||null);setPreview(false);setTestToken(null);setTestRoute([]);setHistory([]);setFuture([]);setMessage(d.version<6?"Older map imported and upgraded to literal-foot elevation and vector barriers.":"Map imported successfully.");}catch{setMessage("That file is not a valid Shattered Crown map.");}};reader.readAsText(file);};
 const loadDust2=()=>{if((history.length||tiles.some(tile=>tile.kind!=="void")||barriers.length)&&!confirm("Replace the current Forge draft with the full-resolution Dust 2 image, imported vectors, and exact-foot elevation data?"))return;setName("Dust 2");setWidth(DUST2_COLS);setHeight(DUST2_ROWS);setTiles(dust2EditorTiles());setEdges([]);setBarriers(cloneBarriers(dust2Barriers));setReference(DUST2_IMAGE);setOpacity(.82);setZoom(24);setPreview(false);setShowTileData(true);setShowBarrierLayer(true);setShowElevationLayer(true);setShowGridLayer(true);setFreeClimb(true);setTestToken(null);setTestRoute([]);setHistory([]);setFuture([]);setMessage(`Dust 2 loaded: ${dust2Barriers.length} source vectors, including open doors, with authored elevation preserved to the foot from -10 to +30 ft.`);};
 const testStart=()=>{const marked=tiles.findIndex(tile=>tile.marker?.kind==="party-start"&&!((tile.blocked??blockedDefault.has(tile.kind))));const open=marked>=0?marked:tiles.findIndex(tile=>!(tile.blocked??blockedDefault.has(tile.kind)));return open<0?null:{x:open%width,y:Math.floor(open/width)};};
 const togglePreview=()=>{if(preview){setPreview(false);setSightProbe(false);setTestSightTarget(null);setTestSightVisible(null);setMessage("Returned to editor layers.");return;}const start=testStart();if(!start){setMessage("Add an open square before starting playtest.");return;}setTestToken(start);setTestRoute([start]);setTestSightTarget(null);setTestSightVisible(null);setPreview(true);setShowBarrierLayer(false);setShowElevationLayer(true);setShowGridLayer(true);setFreeClimb(true);setSightProbe(false);setMessage("Playtest active with Player View. Hidden geometry stays concealed; turn Walls on only when debugging.");};
 const probeSight=(index:number)=>{const source=testToken||testStart();if(!source)return;const target={x:index%width,y:Math.floor(index/width)},observer=editorPlaytestObserver({point:source,width,tiles:editorTestTiles}),targetPosition=editorPlaytestTarget({point:target,width,tiles:editorTestTiles}),blocked=editorVisionKernel.blocksSight(observer,targetPosition,{allowOpaqueTarget:true}),fromElevation=observer.elevationFt||0,toElevation=targetPosition.elevationFt||0;setTestSightTarget(target);setTestSightVisible(!blocked);setMessage(`${!blocked?"VISIBLE":"HIDDEN"}: observer ${fromElevation} ft → target ${toElevation} ft. Sight Probe uses the same exact-foot, sub-square vision kernel as Player View.`);};
 const moveTestToken=(index:number)=>{if(!preview)return;const start=testToken||testStart();if(!start){setMessage("No open starting square is available.");return;}const goal={x:index%width,y:Math.floor(index/width)},route=findEditorPlaytestRoute({width,height,start,goal,tiles:editorTestTiles,edges,barriers,freeClimb});if(!route){setTestRoute([]);setMessage(`Blocked route to ${goal.x},${goal.y}. Turn on wall and elevation overlays to see why.`);return;}const fallDice=route.slice(1).reduce((total,point,routeIndex)=>total+fallDiceForDrop((tiles[route[routeIndex].y*width+route[routeIndex].x]?.elevationFt||0)-(tiles[point.y*width+point.x]?.elevationFt||0)),0);setTestToken(goal);setTestRoute(route);setTestSightTarget(null);setTestSightVisible(null);setMessage(`Walked ${Math.max(0,route.length-1)} squares to ${goal.x},${goal.y} at ${tiles[index].elevationFt||0} ft.${fallDice?` Fall preview: ${fallDice}d6.`:""}`);};
 const loadReference=(file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>{setReference(String(r.result));setMessage("Reference image loaded. Use opacity and zoom to line up the grid.");};r.readAsDataURL(file);};
 return <main className={`editor-shell ${preview?"is-playtesting":""}`} onMouseUp={endStroke} onMouseLeave={endStroke}>
  <header className="editor-header">
   <div><p className="eyebrow">SHATTERED CROWN · LEVEL FORGE</p><label className="editor-name-label">MAP NAME<input className="editor-name" value={name} onChange={e=>setName(e.target.value)} aria-label="Map name"/></label></div>
   <div className="editor-header-actions"><button onClick={onExit}>← Game Menu</button><button onClick={loadDust2}>Load Dust 2</button><button onClick={()=>importRef.current?.click()}>Import</button><button onClick={resetMap} title="Clear this draft and restore the blank starter map">Reset to Default</button><button onClick={doubleMap} title="Turn every square into a 2 × 2 playable area">Double Map ×2</button><button className={preview?"selected":""} onClick={togglePreview}>{preview?"Exit Playtest":"Enter Playtest"}</button><button onClick={exportElevation}>Export Elevation</button><button className="primary" onClick={exportMap}>Export Map</button></div>
  </header>
  <section className="editor-layout">
   <aside className="editor-panel">
    <p className="panel-title">FREE-FLOATING BARRIERS</p>
    <ToolButtons items={[{kind:"free-wall-line",icon:"╱",label:"Vector wall"},{kind:"free-terrain-line",icon:"◒",label:"Terrain cover"},{kind:"free-door-line",icon:"┄",label:"Vector door"},{kind:"free-secret-door-line",icon:"╱?",label:"Secret barrier"},{kind:"erase-free-line",icon:"⌫",label:"Barrier eraser"}]} brush={brush} onSelect={setBrush}/>
    <label className="barrier-height-input">Barrier height <span><input type="number" min="5" max="100" step="5" value={wallHeightFt} onChange={event=>setWallHeightFt(Math.max(5,Math.min(100,Number(event.target.value)||5)))}/> ft</span></label>
    <p className="panel-help">Drag directly over the image at any angle. Walls stop movement and sight. Terrain cover stays walkable, but two crossed edges hide whatever is behind it. Nearby endpoints magnetically join.</p>
    <p className="panel-title">GRID-EDGE LINES</p>
    <ToolButtons items={[{kind:"wall-line",icon:"━",label:"Snapped wall",key:"W"},{kind:"door-line",icon:"┄",label:"Snapped door",key:"D"},{kind:"secret-door-line",icon:"━?",label:"Secret door"},{kind:"erase-line",icon:"⌫",label:"Edge eraser"}]} brush={brush} onSelect={setBrush}/>
    <p className="panel-help">Legacy corner-snapped lines remain available for older maps.</p>
    <p className="panel-title">DUNGEON GEOMETRY</p><ToolButtons items={geometry} brush={brush} onSelect={setBrush}/>
    <p className="panel-title">OUTDOOR TERRAIN & OBJECTS</p><ToolButtons items={outdoors} brush={brush} onSelect={setBrush}/>
    <p className="panel-title">ELEMENTAL TERRAIN</p><ToolButtons items={elements} brush={brush} onSelect={setBrush}/>
    <p className="panel-title">ELEVATION</p><ToolButtons items={elevations} brush={brush} onSelect={setBrush}/>
    <label className="barrier-height-input">Exact elevation <span><input type="number" min="-500" max="500" step="1" value={exactElevationFt} onChange={event=>setExactElevationFt(Math.max(-500,Math.min(500,Number(event.target.value)||0)))}/> ft</span></label><button className="wide ghost" onClick={()=>setBrush(`elevation-${exactElevationFt}` as Brush)}>Paint exact height</button>
    <p className="panel-help">Elevation is stored to the foot. Choose a preset or enter exact feet, then click-drag to paint. Alt-click or right-click any square to copy its current height. Undo is Ctrl/Cmd-Z.</p>
    <p className="panel-title">MOVEMENT</p><ToolButtons items={[{kind:"blocked",icon:"⊘",label:"Force blocked"},{kind:"unblocked",icon:"○",label:"Force open"}]} brush={brush} onSelect={setBrush}/>
    <p className="panel-title">ENCOUNTER MARKERS</p><ToolButtons items={markers} brush={brush} onSelect={setBrush}/>
   </aside>
   <section className="editor-workspace">
    <div className="editor-toolbar">
     <span>{preview?"PLAYTEST · PLAYER VIEW":"Canvas"}</span>
     {!preview&&<><input type="number" min="8" max="120" value={width} onChange={e=>setWidth(+e.target.value)} aria-label="Map width"/><b>×</b><input type="number" min="8" max="120" value={height} onChange={e=>setHeight(+e.target.value)} aria-label="Map height"/><button onClick={resize}>Resize</button><span className="divider"/><button onClick={undo} disabled={!history.length}>↶ Undo</button><button onClick={redo} disabled={!future.length}>↷ Redo</button><button onClick={()=>setShowTileData(v=>!v)}>{showTileData?"Hide tile data":"Show tile data"}</button></>}
     {preview&&<><button className={showBarrierLayer?"selected":""} onClick={()=>setShowBarrierLayer(value=>!value)}>Walls {showBarrierLayer?"ON":"OFF"}</button><button className={showElevationLayer?"selected":""} onClick={()=>setShowElevationLayer(value=>!value)}>Elevation {showElevationLayer?"ON":"OFF"}</button><button className={showGridLayer?"selected":""} onClick={()=>setShowGridLayer(value=>!value)}>Grid {showGridLayer?"ON":"OFF"}</button><button className={freeClimb?"selected":""} onClick={()=>{setFreeClimb(value=>!value);setTestRoute(testToken?[testToken]:[]);}}>Free Climb {freeClimb?"ON":"OFF"}</button><button className={sightProbe?"selected":""} onClick={()=>{setSightProbe(value=>!value);setTestSightTarget(null);setTestSightVisible(null);}}>Sight Probe {sightProbe?"ON":"OFF"}</button></>}
     <span className="divider"/><label>Zoom <input type="range" min="18" max="54" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><b>{zoom}px</b>
     <span className="layer-note">{preview?"Click a destination to test a real routed walk":lineKinds.has(brush)?"Corner Assist is on — drag near corners":freeLineKinds.has(brush)?"Exact vector mode — no grid snapping":"Markers, terrain, height and blocking are separate layers"}</span>
    </div>
    <div className={`editor-viewport ${preview?"preview-mode":""}`}>
     <div className={`editor-canvas ${reference?"has-reference-image":""} ${lineKinds.has(brush)?"line-brush-active":""} ${freeLineKinds.has(brush)?"free-line-brush-active":""} ${preview&&showElevationLayer?"show-elevation-layer":""} ${preview&&!showGridLayer?"hide-grid-layer":""}`} onPointerDown={startLine} onPointerMove={moveLine} onPointerLeave={()=>setSnapVertex(null)} onPointerUp={endStroke} onPointerCancel={endStroke} style={{width:width*zoom,height:height*zoom,gridTemplateColumns:`repeat(${width}, ${zoom}px)`,gridTemplateRows:`repeat(${height}, ${zoom}px)`,backgroundImage:reference?`linear-gradient(rgba(8,9,7,${preview?.06:1-opacity}),rgba(8,9,7,${preview?.06:1-opacity})),url(${reference})`:undefined,backgroundSize:"100% 100%",backgroundRepeat:"no-repeat"}}>
      {tiles.map((tile,i)=>{const blocked=tile.blocked??blockedDefault.has(tile.kind),tileKey=`${i%width},${Math.floor(i/width)}`,feet=tile.elevationFt||0,sampleHeight=()=>{setExactElevationFt(feet);setBrush(`elevation-${feet}` as Brush);setMessage(`Copied ${feet} ft from ${i%width},${Math.floor(i/width)}. Click-drag to paint that exact height.`);};return <button key={i} className={`editor-tile tile-${tile.kind} height-${Math.round(feet/5)} ${blocked?"is-blocked":""} ${tile.marker?"has-marker":""}`} data-elevation={feet} aria-label={`${i%width},${Math.floor(i/width)} ${tile.kind} elevation ${feet} feet${blocked?" blocked":""}`} onContextMenu={e=>{if(preview)return;e.preventDefault();sampleHeight();}} onMouseDown={e=>{e.preventDefault();if(preview){if(sightProbe)probeSight(i);else moveTestToken(i);return;}if(e.altKey){sampleHeight();return;}if(drawingKinds.has(brush))return;setPainting(true);paint(i);}} onMouseEnter={()=>!preview&&painting&&!markerKinds.has(brush)&&brush!=="note"&&!drawingKinds.has(brush)&&paint(i)}><span className="terrain-icon">{icon(tile.kind)}</span>{((!preview&&showTileData&&feet!==0)||(preview&&showElevationLayer&&feet!==0))&&<em className="height-badge editor-elevation-label">{feet>0?`+${feet}`:feet} ft</em>}{!preview&&showTileData&&blocked&&<em className="blocked-badge">×</em>}{tile.marker&&<b className={`marker marker-${tile.marker.kind}`} title={tile.marker.group||tile.marker.label}>{icon(tile.marker.kind)}<small>{tile.marker.group||tile.marker.label}</small></b>}{(!preview||showBarrierLayer)&&(edgesByTile.get(tileKey)||[]).map(edge=><i key={`${edge.side}-${edge.kind}`} className={`editor-edge edge-${edge.side} edge-${edge.kind}`}/>)}{!preview&&showTileData&&<small className="coordinate">{i%width},{Math.floor(i/width)}</small>}</button>;})}
      {preview&&playtestVision&&<MapEditorVisionOverlay layer={playtestVision} width={width} height={height} tileSize={zoom}/>}
      <svg className="free-barrier-layer" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-label={`${barriers.length} free-floating barriers`}>
       {(!preview||showBarrierLayer)&&barriers.map(barrier=>{const measured=barrier.bottomFt!==undefined||barrier.topFt!==undefined;return <line key={barrier.id} className={`free-barrier barrier-${barrier.kind} ${barrier.open?"is-open":""} ${measured?"height-limited":""}`} x1={barrier.a.x} y1={barrier.a.y} x2={barrier.b.x} y2={barrier.b.y} vectorEffect="non-scaling-stroke"><title>{barrier.open?"open door · non-blocking":`${barrier.kind} · ${measured?`${barrier.bottomFt??"−∞"}–${barrier.topFt??"+∞"} ft`:`${barrier.heightFt||10} ft high`}`}</title></line>;})}
       {!preview&&freeBarrierDraft&&<line className={`free-barrier free-barrier-draft barrier-${freeBarrierDraft.kind}`} x1={freeBarrierDraft.a.x} y1={freeBarrierDraft.a.y} x2={freeBarrierDraft.b.x} y2={freeBarrierDraft.b.y} vectorEffect="non-scaling-stroke"/>}
       {preview&&testRoute.length>1&&<polyline className="editor-test-route" points={testRoute.map(point=>`${point.x+.5},${point.y+.5}`).join(" ")} vectorEffect="non-scaling-stroke"/>}
       {preview&&testToken&&testSightTarget&&<line className={`editor-sight-ray ${testSightVisible?"visible":"blocked"}`} x1={testToken.x+.5} y1={testToken.y+.5} x2={testSightTarget.x+.5} y2={testSightTarget.y+.5} vectorEffect="non-scaling-stroke"/>}
      </svg>
      {preview&&testToken&&<i className="editor-test-token" style={{left:(testToken.x+.5)*zoom,top:(testToken.y+.5)*zoom}} title={`Playtest token at ${testToken.x},${testToken.y}`}>◆</i>}
      {preview&&testSightTarget&&<i className={`editor-sight-target ${testSightVisible?"visible":"blocked"}`} style={{left:(testSightTarget.x+.5)*zoom,top:(testSightTarget.y+.5)*zoom}}>{testSightVisible?"VISIBLE":"HIDDEN"}</i>}
      {lineKinds.has(brush)&&snapVertex&&!preview&&<i className="corner-assist" style={{left:snapVertex.x*zoom,top:snapVertex.y*zoom}}/>}
     </div>
    </div>
    <div className="editor-status"><span>{message}</span><b>{counts.forest} forest · {counts.raised} raised · {counts.markers} markers · {counts.barriers} barriers</b></div>
   </section>
   <aside className="editor-panel reference-panel">
    <p className="panel-title">REFERENCE IMAGE</p><button className="wide" onClick={()=>fileRef.current?.click()}>{reference?"Replace image":"Load map image"}</button>
    {reference?<><label className="range-label">Overlay visibility <b>{Math.round(opacity*100)}%</b><input type="range" min="0" max="1" step=".05" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label><button className="wide ghost" onClick={()=>setReference(null)}>Remove image</button></>:<p className="panel-help">Optional: load an image and draw exact barriers over it. The image remains visible in Playtest.</p>}
    <p className="panel-title">MAP WORKFLOW</p><ol><li>Load Dust 2 or your own reference image.</li><li>Trace collision, terrain cover, and sight with free-floating barriers.</li><li>Paint terrain and elevation to the foot.</li><li>Place party, spawn, objective, and exit markers.</li><li>Enter Playtest and click destinations to test routing and falls.</li><li>Turn on Sight Probe, then click a target to test 3D visibility.</li><li>Export one JSON per encounter map.</li></ol>
    <p className="panel-help"><b>Older Level Forge maps still import.</b> Version 6 stores literal feet and exact vector barriers while retaining every snapped edge.</p><div className="editor-save"><i>●</i><span>Draft autosaved<br/><small>on this device</small></span></div>
   </aside>
  </section>
  <input hidden ref={fileRef} type="file" accept="image/*" onChange={e=>loadReference(e.target.files?.[0])}/><input hidden ref={importRef} type="file" accept="application/json,.json" onChange={e=>loadMap(e.target.files?.[0])}/>
 </main>;
}
